Repository aai-institute/lakefs-spec, pull requests merged in 2023-12, with the labels that each got.

#196 Docs: Add call to action for early adopters to README and landing page [ENG-186]
  README.md
  docs/index.md
  requirements-dev.txt
  requirements-docs.txt
Labels: documentation

#198 `ls`: Make non-recursive by default, correctly update dircache
  src/lakefs_spec/client_helpers.py
  src/lakefs_spec/spec.py
  tests/test_client_helpers.py
  tests/test_ls.py
Labels: bug

#221 Add overloads for `LakeFSFileSystem.ls()`
  src/lakefs_spec/spec.py
Labels: enhancement

#226 Fix transaction doc on `Placeholder` values
  docs/guides/transactions.md
  mkdocs.yml
Labels: documentation
